### ISSUE TITLE
Setnour6's 2024 Checklist of Pre-Release tasks

### ISSUE THREAD

**Issue by Setnour6** [Solaestas/Everglow#241]
This is an updated and more modern approach of #4. Not everything may be applied to or changed for the mod, so do not expect much of this list.

- [ ] Go through all of the items to check for balancing, adding/changing sounds, and some functionality.
- [ ] Add a sound for when the Falling Large Bulbs land on the ground. The given terraria sounds (such as when a slime dies) should work.

**Tasks for Thoughts and Concerns:**

- [ ] Change the subworld loading background texture to not display or load when the Everglow Mod Menu is chosen to display. Maybe a mod menu variable boolean for when it is active could work.
