### ISSUE TITLE
Setnour6's Checklist of Ideas, To-Do's, and Ports

### ISSUE THREAD

**Issue by Setnour6** [Solaestas/Everglow#4]
Ports, Ideas and To-Do's listed may not all be considered, and therefore not all of the listed Ports, Ideas and To-Do's will apply. Ports, Ideas and To-Do's can and will change with time, potentially staying on the list or not

**TO DO**:
- Port all of the MythMod content (including optimizations)
    - [x] Clubs (MythModule)
    - [x] Slingshots (MythModule)
    - [ ] Legendary Weapons (MythModule)
    - [ ] Mythic/Endgame Weapons (MythModule)
    - [ ] Other weapons (I forgot what else there was)
    - [x] Picked up plants (MythModule or PlantModule?)
    - [ ] Boss Accessories (MythModule)
    - [x] Non-boss Accessories (MythModule or PlantModule, depending on accessory type?)
    - [ ] Boss Trophies (MythModule)
    - [ ] Other items and tiles (varies)
    - [ ] Other things I didn't cover (varies)

- Port all of the Eternal Resolve content (including optimizations)
    - [ ] Ekanda
    - [ ] Destiny Content
    - [ ] Gacha system
    - [x] Bayonets
    - [ ] Bosses
    - [ ] Other items

- Port and fix other things
    - [ ] Port the Ocean World
    - [ ] Complete localization entries
    - [ ] The Tusk's new background music
    - [ ] The Tusk's new tension music
    - [ ] The Tusk's new fight music
    - [ ] Rework the Cursed Jaw/Tusk Biome
    - [ ] Rework the Lantern Moon event
    - [ ] Rework the Dash Core
    - [ ] Rework the Lantern Ghost King
    - [x] Fix underworld from being hidden in the normal world
    - [ ] Map entries for all firefly tiles work properly
    - [ ] Improve compatibility with "For The Worthy" and "Zenith/Get Fixed Boi"

Internal Specific:
- [] Fully define and declare all modules with proper loading/unloading for content-choosing (Example: Myth Module is disabled and won't load anything, meaning no items, tiles, or anything else from Myth, but Yggdrasil is enabled and will load everything)

Branch Specific:
- [x] Firefly world biome generates with the cocoon in how it is intended (to be discussed or clarified further)

___

**Ideas**:
- An item that summons the Corrupted Moth boss (and other bosses) as a minion/pet (In both Master Mode and For The Worthy only)
    - The Corrupted Moth won't die in Master Mode For The Worthy and will instead fly away or end the fight, but still drop items as normal.
- Town pets can interact with other NPCs and the player and display hearts when petted (In a new module)
- Acytaea can only be challenged after defeating all of the pre-zenith bosses
- Acytaea drops her own weapons upon defeat (Master Mode or For The Worthy only?)
- A gate that generates in the Firefly biome and activates after defeating all pre-hardmode bosses (or just Skeletron)
- Subworlds also have seed effects applied to them
- New water bolt book's right click will not teleport but will instead make the player dash fast towards the cursor
- A firefly biome armor set bonus effect that increases the power of some firefly weapons and items when in the firefly biome (Post-CMoth probably? To be discussed further), indicated by an effect to the item in inventory.
- Firefly biome still generates in the normal world, and the firefly subworld/affiliated world can also exist too.
- The sky on the surface turns dark and blue lights float in the background during the Corrupted Moth fight (if the player is on the surface), and can be toggled.
- Corrupted Scales' reworked projectiles to shoot dust of varying sizes instead of simply circles of dust, and also shoots scales.
- **Developer item suggestion**: a microphone which functions like a flail and summons music notes (when I tried to make it myself, I had a hard time and it didn't work).
    - **Attack 1**: normal flail action with some music note appearances. **Attack 2**: Releasing the flail fires notes that stay for 5 seconds or until touched. **Attack 3:** Clicking again returns the flail as usual.

Branch Specific:
- WindMoveSeed (Aeolus Seed) can function as a small dash item (consumed on use) by pressing shift (or any other key)
- Dreamweaver has a unique attack, instead of copying Corrupted Scales' attack completely (which might be worked on but Omni said that it's finished)
    -  Dreamweaver can shoot a few dream strings or dream anything, which literally creates something or homes into enemies, or can summon attack moths like the Lepidoptera Blade, or maybe shoot blue flames. Have it do anything.

Item specific (Thank you Lacewing for giving me more ideas):
- MothEye / Ommateum of the Moth bonus granting ideas: Vision related
    -  ScaleWingBlade / Lepidoptera Blade moths have longer lifespan and better homing capabilities, or moth speed increase, and NPC detection range increase, or maybe better crit chance (see the weaknesses). Currently, the blade summons more moths. (**done**)
    - Shadow Wing Bow's moth arrows have higher crit chance, or faster charging, or reduce shot spread. (**done**)
    - Phosphorescent Gun does not push the player back.
    - Evil Chrysalis / Cocoon Staff moths damage does not reduce after the right click attack.
    - Corrupted Scales now fires scales at times (joking), Improving the dust projectiles, or faster projectile.
    - Bead Gun might not have bonuses because it's too powerful.
    - Darkness Fan's moths have better homing capabilities or last longer. (**done**)
    - Navy Blue's projectiles explode faster, or is larger, and more flame projectiles appear.
    - Dreamweaver might not have bonuses because it's too powerful.
    - Firefly armor increases player's knockback resistance, or prevents the player from getting the darkness debuff.

Seed specific (including 1.4.4 seed effect proposals):
    - Corrupted Moth is faster and has a special moth wall attack in "For the Worthy"
    - Corrupted Moth summons Phantom Moths throughout the fight in "For the Worthy"
    - Corrupted Moth fires even more projectiles in "Legendary Mode"
    - Corrupted Moth has a special beam attack in "Get Fixed Boi!"
    - Bloody Tusk has new attacks in "For the Worthy"
    - Bloody Tusk's attacks fill more of the area in "Legendary Mode"
    - Bloody Tusk's walls now move immediately in "Legendary Mode"
    - Bloody Tusk is a nightmare to deal with in "Get Fixed Boi!" (I don't have an actual idea for this one)
    - Acytaea has new attacks in "For the Worthy"
    - Acytaea's attacks will instantly kill the player in "Legendary Mode"
    - Acytaea reveals her true form in "Wor the Worthy"
    - Acytaea is even more challenging in "Get Fixed Boi!" (I don't have an actual idea for this one)
___

**Ports**

_Item Ports:_
Accessories:
- [ ] BloodHeartStone
- [x] BlueGel
- [ ] BlueTorchFlower
- [x] CorruptEye
- [x] CyanBranch
- [x] CyanPetal
- [x] DarkHat
- [x] DukeTooth
- [x] FlameBorageBadge (Ported as FireflyBorageBadge. Pending Adjustments)
- [x] GoldLiquidPupil
- [x] GoldRound
- [x] GreenGel
- [x] HotPinkCrown
- [x] JungleVitamin
- [x] LightPurplePen
- [x] ManyWhiteFlower
- [x] MothEye (Pending adjustments)
- [x] Odd8Ring
- [x] OrangeCrown
- [ ] OrangeStick
- [x] PinkFourPedal
- [x] PurpleBall
- [ ] PurpleReedHalo
- [x] RedGel
- [x] RedTriangle
- [x] SilverCupFlower
- [x] TuskLace
- [x] WalnutClip
- [x] WhiteCrown
- [x] WhitePedal
- [x] WhiteWoodFlower
- [x] WindMoveSeed
- [x] YellowBellFlower

For now, I will leave it like this. If the amount of tasks listed bothers you, please let me know if you want me to move the ports section to another issue (or you can make it if you want to)
